title: Chengyi Wang
email: cywang@mail.nankai.edu.cn
description: >- # this means to ignore newlines until "baseurl:"
  Hi! I am a joint PhD student of Nankai University and Microsoft Research Asia (MSRA) supervised by Prof. Ming Zhou. Currently, I am working as an intern at NLC group of MSRA.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  cywang97

# Build settings
markdown: kramdown
remote_theme: ngzhio/jekyll-theme-hamilton
plugins:
  - jekyll-remote-theme

author: Chengyi Wang


