title: Chengyi Wang (王程一)
email: cywang@mail.nankai.edu.cn
description: >- # this means to ignore newlines until "baseurl:"
author: Chengyi Wang
avatar: /logo.png

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  cywang97

paginate: 10



# Build settings
markdown: kramdown
remote_theme: ngzhio/jekyll-theme-hamilton
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

logo: logo.png
social:
  name: Chengyi Wang
  links:
    - https://github.com/cywang97




